name: Memo Rogue
favicon: null
layout_spectrum: 0.46568
typography_spectrum: 1
title: Memo Rogue
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fc9aa7'
    - '#e06b84'
    - '#ffffff'
    - '#fdb8c1'
    - '#222222'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.5893485757987946
purpose: []
