name: Memo Rogue
favicon: null
layout_spectrum: 0.49553
typography_spectrum: 1
title: Memo Rogue
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#212222'
    - '#e16a84'
    - '#ffffff'
    - '#7e7b7a'
    - '#6f404a'
  brandStrength: 0.9879063640255481
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.5893485757987946
purpose: []
